---
- name: Ensure vim directory exists.
  file:
    path: ~/.vim
    state: directory

- name: Clone NERDtree vim plugin.
  git:
    repo: https://github.com/preservim/nerdtree.git
    dest: ~/.vim/pack/vendor/start/nerdtree
    version: master
    accept_hostkey: true
  register: nerdtree_clone
  become: false

- name: Enable NERDtree helptags
  command: vim -u NONE -c "helptags ~/.vim/pack/vendor/start/nerdtree/doc" -c q
  when: nerdtree_clone.changed

- name: Clone Airline vim plugin.
  git:
    repo: https://github.com/vim-airline/vim-airline.git
    dest: ~/.vim/pack/dist/start/vim-airline
    version: master
    accept_hostkey: true
  register: airline_clone
  become: false

- name: Enable Airline helptags
  command: vim -u NONE -c "helptags ~/.vim/pack/dist/start/vim-airline/doc" -c q
  when: airline_clone.changed

- name: Get current Terminal profile.
  command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  copy:
    src: files/terminal/Lents.terminal
    dest: /tmp/Lents.terminal
  changed_when: false
  when: "'Lents' not in terminal_theme.stdout"

# Needed to run: xattr -d com.apple.quarantine /tmp/Lents.terminal
# Terminal theme needs to be signed, apparently...
- name: Ensure custom Terminal profile is added.
  command: xattr -d com.apple.quarantine /tmp/Lents.terminal && open /tmp/Lents.terminal
  changed_when: false
  when: "'Lents' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  command: '{{ item }}'
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string Lents
    - defaults write com.apple.terminal 'Startup Window Settings' -string Lents
  changed_when: false
  when: "'Lents' not in terminal_theme.stdout"

- name: Fetch Oh My Zsh installer.
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: '{{ downloads }}/zsh-installer.sh'
    mode: u+x

# - name: Install Oh My Zsh
#   command: '{{ downloads }}/zsh-installer.sh'
#   changed_when: false
