#!/bin/bash

code --install-extension azblockchain.azure-blockchain
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-dotnettools.csharp
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension msjsdiag.vscode-react-native
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-test
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension platformio.platformio-ide
code --install-extension golang.go
code --install-extension graphql.vscode-graphql
code --install-extension rust-lang.rust
code --install-extension samuelcolvin.jinjahtml
code --install-extension coenraads.bracket-pair-colorizer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension mikestead.dotenv
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension exiasr.hadolint
code --install-extension yzhang.markdown-all-in-one
code --install-extension davidanson.vscode-markdownlint
code --install-extension pkief.material-icon-theme
code --install-extension teclado.vscode-nginx-format
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension sdras.night-owl
code --install-extension christian-kohler.path-intellisense
code --install-extension foxundermoon.shell-format
code --install-extension timonwong.shellcheck
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension eamodio.gitlens
